"""The 2D operator table, generated by asking cinderx rather than by hand.

`a op b` is the one place where a result cannot be derived from one input.
`int64 + int64` is int64, `list * int` is list, `str % x` is str, and no rule
that looks at the operator alone or at either operand alone gets all three
right. So the resolution is a lookup keyed on *both* operand types.

Writing that table by hand would be a second implementation of Static Python's
promotion rules, and a second implementation is a second thing to be wrong.
Instead the table is generated: for each pair of types, bind a probe module
that applies every operator to a value of each, and read the answers out of
`expr_types`. The rules stay cinderx's; this file only records them.

Types are keyed by `type_descr` -- ('builtins', 'int', '!') -- because every
bind builds a fresh Compiler, so `Value` objects cannot be compared or cached
across runs. `value_for` maps a descr back to a live instance in whatever
type_env is current.
"""
from ast import (Add, Sub, Mult, Div, FloorDiv, Mod, Pow, LShift, RShift,
                 BitOr, BitAnd, BitXor, BinOp, Compare, Eq, NotEq, Lt, LtE,
                 Gt, GtE, parse, walk)
from json import dump, load
from os import path

TABLE_PATH = path.join(path.dirname(path.abspath(__file__)), "data",
                       "dunder_table.json")

BIN_OPS = {"+": Add, "-": Sub, "*": Mult, "/": Div, "//": FloorDiv, "%": Mod,
           "**": Pow, "<<": LShift, ">>": RShift, "|": BitOr, "&": BitAnd,
           "^": BitXor}
CMP_OPS = {"==": Eq, "!=": NotEq, "<": Lt, "<=": LtE, ">": Gt, ">=": GtE}
OPS = {**BIN_OPS, **CMP_OPS}

OP_OF = {op: sym for sym, op in OPS.items()}

# One expression per type, used to give the probe a value of that type. A few
# cannot be written as an annotation on a parameter, so they are built inline.
PRIMS = ["int8", "int16", "int32", "int64",
         "uint8", "uint16", "uint32", "uint64", "double", "cbool"]
BUILTINS = ["int", "float", "bool", "str", "bytes", "list", "tuple", "set",
            "dict", "object"]
TYPES = BUILTINS + PRIMS

PROBE = """from __static__ import {prims}
def _probe(a: {left}, b: {right}) -> None:
{body}
"""


def _probe_source(left, right, syms):
    body = "\n".join(f"    a {s} b" for s in syms) or "    pass"
    return PROBE.format(prims=", ".join(PRIMS), left=left, right=right, body=body)


def descr_of(t):
    k = getattr(t, "klass", None)
    try:
        d = getattr(k, "type_descr", None)
    except Exception:
        return None                       # awaitables and friends have none
    return list(d) if d is not None else None


def _probe(get_ast_data, left, right, syms):
    """Bind one probe module and read off each operator's result.

    `bind` is all-or-nothing: one illegal combination and the whole module
    raises. So a failing batch is retried one operator at a time, and the ones
    that genuinely have no result are simply absent from the table -- which is
    the right answer for them, since cinder rejects the program.
    """
    src = _probe_source(left, right, syms)
    try:
        data = get_ast_data(parse(src))
    except Exception:
        if len(syms) == 1:
            return {}
        out = {}
        for s in syms:
            out.update(_probe(get_ast_data, left, right, [s]))
        return out
    types, tree = data.types, data.tree
    out = {}
    for n in walk(tree):
        if isinstance(n, BinOp):
            sym = OP_OF.get(type(n.op))
        elif isinstance(n, Compare) and len(n.ops) == 1:
            sym = OP_OF.get(type(n.ops[0]))
        else:
            continue
        d = descr_of(types.get(n))
        if sym is not None and d is not None:
            out[sym] = d
    return out


def build_table(get_ast_data):
    """(left, right) -> {operator: result descr}, one probe module per pair."""
    table = {}
    for left in TYPES:
        for right in TYPES:
            got = _probe(get_ast_data, left, right, list(OPS))
            if got:
                table[f"{left}|{right}"] = got
    return table


def load_table(get_ast_data=None, rebuild=False):
    if not rebuild and path.exists(TABLE_PATH):
        with open(TABLE_PATH) as f:
            return load(f)
    if get_ast_data is None:
        return {}
    table = build_table(get_ast_data)
    with open(TABLE_PATH, "w") as f:
        dump(table, f, indent=1, sort_keys=True)
    return table


_ENV_INDEX = {}


def value_for(descr, type_env):
    """A live instance for a recorded descr, in this run's type_env.

    Values cannot be cached across binds -- each get_ast_data builds its own
    Compiler -- so the table stores names and this resolves them per run.
    """
    key = id(type_env)
    index = _ENV_INDEX.get(key)
    if index is None:
        index = {}
        for name in dir(type_env):
            if name.startswith("_"):
                continue
            try:
                klass = getattr(type_env, name)
            except Exception:
                continue
            try:
                d = getattr(klass, "type_descr", None)
            except Exception:
                continue                  # a few classes refuse to have one
            if d is not None and hasattr(klass, "instance"):
                index.setdefault(tuple(d), klass.instance)
        _ENV_INDEX[key] = index
    return index.get(tuple(descr))


def result_of(table, op, left_descr, right_descr, type_env):
    """The settled type of `left op right`, or None if the table has no row."""
    sym = OP_OF.get(type(op))
    if sym is None or left_descr is None or right_descr is None:
        return None
    row = table.get(f"{_key(left_descr)}|{_key(right_descr)}")
    if row is None:
        return None
    d = row.get(sym)
    return None if d is None else value_for(d, type_env)


def _key(descr):
    """The probe name a descr corresponds to: ('builtins','int','!') -> int."""
    return descr[1] if len(descr) > 1 else descr[0]
