"""Find the smallest surviving subset of wrappers generated by the Dimmer.

Unlike solve_and_apply.py's speculative graph reduction, this starts from the
real, known-good detyper output. It identifies coercion calls that were not in
the author's source, enumerates subsets in increasing retained-wrapper count,
removes the rest, and asks the Static Python loader whether the result is
valid.

The result is globally minimal only within the finite set of wrapper positions
chosen by the existing mediator. It does not discover alternative placements.
"""
from __future__ import annotations

import argparse
import ast
import copy
import itertools
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from detyper import detype
from import_adder import add_imports

sys.path.insert(0, str(ROOT / "_cinderx/cinderx/PythonLib"))
from cinderx.compiler.errors import CollectingErrorSink
from cinderx.compiler.static import StaticCodeGenerator
from cinderx.compiler.static.compiler import Compiler

# Calls that are pure representation adaptations and can be peeled back to
# their operand. `clen` and `Array` are deliberately absent: they compute or
# allocate rather than merely adapting an existing value.
ONE_ARG = {
    "box", "unbox", "cbool", "double",
    "int8", "int16", "int32", "int64",
    "uint8", "uint16", "uint32", "uint64",
}


def called_name(call: ast.Call) -> str | None:
    func = call.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return None


def call_key(call: ast.Call) -> tuple:
    return (
        getattr(call, "lineno", None),
        getattr(call, "col_offset", None),
        getattr(call, "end_lineno", None),
        getattr(call, "end_col_offset", None),
        called_name(call),
    )


def removable_operand(call: ast.Call):
    name = called_name(call)
    if name in ONE_ARG and len(call.args) == 1:
        return call.args[0]
    if name == "cast" and len(call.args) == 2:
        return call.args[1]
    return None


def mark_generated_wrappers(original_source: str, transformed: ast.AST):
    """Which calls in the output the mediator put there.

    Identity is the call's shape, not its position. `call_key` carries line and
    column, and every pass rewrites the tree, so an author-written `int64(nb)`
    stopped matching itself and was marked as generated - which meant
    `baseline_tree` stripped the author's own cast out of the program the
    solvers search. They then re-derived it and were charged for it: on
    index_wrap that turned an exact reproduction of the mediator into a
    three-wrap "loss". Two identical author calls are indistinguishable this
    way, which costs an unused candidate; position cost correctness.
    """
    original_calls = {
        ast.unparse(node)
        for node in ast.walk(ast.parse(original_source))
        if isinstance(node, ast.Call)
    }
    candidates = []
    for node in ast.walk(transformed):
        if (isinstance(node, ast.Call)
                and removable_operand(node) is not None
                and ast.unparse(node) not in original_calls):
            node._optimal_candidate = len(candidates)
            candidates.append(node)
    return candidates


class KeepSubset(ast.NodeTransformer):
    def __init__(self, retained: set[int]):
        self.retained = retained

    def visit_Call(self, node):
        self.generic_visit(node)
        index = getattr(node, "_optimal_candidate", None)
        if index is not None and index not in self.retained:
            operand = removable_operand(node)
            if operand is not None:
                return ast.copy_location(operand, node)
        return node


def materialize(base: ast.AST, retained: set[int]) -> str:
    tree = copy.deepcopy(base)
    tree = KeepSubset(retained).visit(tree)
    tree = ast.fix_missing_locations(add_imports(tree))
    return ast.unparse(tree)


def check(source: str, run_program: bool, timeout: int):
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "candidate.py"
        path.write_text(source)
        command = [
            sys.executable,
            str(ROOT / "static_runner.py"),
            str(path),
            "--require-static",
        ]
        if not run_program:
            command.append("--compile-only")
        return subprocess.run(
            command, capture_output=True, text=True, timeout=timeout)


def binds_clean(source: str) -> bool:
    """Does CinderX accept this, without paying for a subprocess?

    A subset that fails to bind cannot pass the loader, and binding in process
    costs milliseconds against the hundreds a `static_runner.py` spawn costs.
    On fannkuch, where the answer turns out to be all ten wrappers and every
    one of the 1024 subsets has to be tried, this is the difference between ten
    minutes and one.
    """
    sink = CollectingErrorSink()
    compiler = Compiler(StaticCodeGenerator, error_sink=sink)
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False
    try:
        compiler.bind("", "", tree, tree, optimize=0)
    except Exception:
        return False
    return not sink.errors


def statement_groups(base, count: int) -> list[list[int]]:
    """Wrapper indices, grouped by the innermost statement holding them.

    A statement is the coarsest thing whose interior the rest of the program
    sees only through the values it produces, which is what makes it a
    plausible seam to cut on. Nine of fannkuch's ten wrappers sit alone in
    theirs, which turns 2^10 subsets into 20.
    """
    inner: dict[int, tuple] = {}
    for statement in ast.walk(base):
        if not isinstance(statement, ast.stmt):
            continue
        for node in ast.walk(statement):
            index = getattr(node, "_optimal_candidate", None)
            if index is None:
                continue
            key = (getattr(statement, "lineno", 0), id(statement))
            if index not in inner or key[0] > inner[index][0]:
                inner[index] = key

    groups: dict[tuple, list[int]] = {}
    for index in range(count):
        groups.setdefault(inner.get(index, (0, 0)), []).append(index)
    return [sorted(members) for _, members in sorted(groups.items())]


def chunked_search(base, count: int, run_program: bool, timeout: int):
    """Minimise each statement's wrappers against the rest held full, then
    verify the combination.

    Decomposition is an assumption, not a theorem - statements are coupled
    through the variables they assign, and the whole lattice is not even
    monotone, so a group's best choice against full neighbours need not be its
    best choice against reduced ones. The combination is therefore checked, and
    a failed check falls back to the exhaustive search rather than being
    reported as an answer.
    """
    groups = statement_groups(base, count)
    everything = set(range(count))
    attempts = 0
    chosen: set[int] = set()

    for group in groups:
        others = everything - set(group)
        best = set(group)
        for size in range(len(group) + 1):
            found = False
            for keep in itertools.combinations(group, size):
                attempts += 1
                if binds_clean(materialize(base, others | set(keep))):
                    best = set(keep)
                    found = True
                    break
            if found:
                break
        chosen |= best

    attempts += 1
    source = materialize(base, chosen)
    if binds_clean(source):
        result = check(source, run_program, timeout)
        if result.returncode == 0:
            return chosen, source, result, attempts, len(groups)
    return None, None, None, attempts, len(groups)


def search(base, count: int, run_program: bool, timeout: int):
    attempts = 0
    spawns = 0
    for retained_count in range(count + 1):
        print(
            f"trying solutions with {retained_count}/{count} wrappers",
            file=sys.stderr,
        )
        for retained_tuple in itertools.combinations(range(count), retained_count):
            attempts += 1
            retained = set(retained_tuple)
            source = materialize(base, retained)
            # The loader is the authority, but it only needs asking about
            # subsets the binder has not already ruled out.
            if not binds_clean(source):
                continue
            spawns += 1
            result = check(source, run_program, timeout)
            if result.returncode == 0:
                print(f"loader spawns: {spawns}", file=sys.stderr)
                return retained, source, result, attempts
    print(f"loader spawns: {spawns}", file=sys.stderr)
    return None, None, None, attempts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--mask", type=lambda value: int(value, 0), default=0)
    parser.add_argument("--benchmark-granularity", action="store_true")
    parser.add_argument("--less-any", action="store_true")
    parser.add_argument("--check", choices=("compile", "run"), default="compile")
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--max-candidates", type=int, default=24)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()

    original = args.source.read_text()
    transformed = detype(
        original,
        mask=args.mask,
        bench=args.benchmark_granularity,
        less_any=args.less_any,
    )
    candidates = mark_generated_wrappers(original, transformed)
    print(f"generated removable wrappers: {len(candidates)}", file=sys.stderr)
    for index, call in enumerate(candidates):
        print(
            f"  w{index}: line {getattr(call, 'lineno', 0)} "
            f"{ast.unparse(call)[:100]}",
            file=sys.stderr,
        )

    if len(candidates) > args.max_candidates:
        raise SystemExit(
            f"refusing 2^{len(candidates)} search; increase --max-candidates"
        )

    retained, output, result, attempts = search(
        transformed,
        len(candidates),
        args.check == "run",
        args.timeout,
    )
    if retained is None:
        raise SystemExit(f"no valid subset after {attempts} attempts")

    print(f"valid after {attempts} attempts", file=sys.stderr)
    print(
        f"minimum retained wrappers: {len(retained)}/{len(candidates)} "
        f"({sorted(retained)})",
        file=sys.stderr,
    )
    if result.stdout.strip():
        print(result.stdout.rstrip(), file=sys.stderr)

    if args.output is None:
        print(output)
    else:
        args.output.write_text(output + "\n")
        print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
