"""Find the smallest surviving subset of wrappers generated by the Dimmer.

Unlike solve_and_apply.py's speculative graph reduction, this starts from the
real, known-good detyper output. It identifies coercion calls that were not in
the author's source, enumerates subsets in increasing retained-wrapper count,
removes the rest, and asks the Static Python loader whether the result is
valid.

The result is globally minimal only within the finite set of wrapper positions
chosen by the existing mediator. It does not discover alternative placements.
"""
from __future__ import annotations

import argparse
import ast
import copy
import itertools
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from detyper import detype
from import_adder import add_imports

# Calls that are pure representation adaptations and can be peeled back to
# their operand. `clen` and `Array` are deliberately absent: they compute or
# allocate rather than merely adapting an existing value.
ONE_ARG = {
    "box", "unbox", "cbool", "double",
    "int8", "int16", "int32", "int64",
    "uint8", "uint16", "uint32", "uint64",
}


def called_name(call: ast.Call) -> str | None:
    func = call.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return None


def call_key(call: ast.Call) -> tuple:
    return (
        getattr(call, "lineno", None),
        getattr(call, "col_offset", None),
        getattr(call, "end_lineno", None),
        getattr(call, "end_col_offset", None),
        called_name(call),
    )


def removable_operand(call: ast.Call):
    name = called_name(call)
    if name in ONE_ARG and len(call.args) == 1:
        return call.args[0]
    if name == "cast" and len(call.args) == 2:
        return call.args[1]
    return None


def mark_generated_wrappers(original_source: str, transformed: ast.AST):
    original_calls = {
        call_key(node)
        for node in ast.walk(ast.parse(original_source))
        if isinstance(node, ast.Call)
    }
    candidates = []
    for node in ast.walk(transformed):
        if (isinstance(node, ast.Call)
                and removable_operand(node) is not None
                and call_key(node) not in original_calls):
            node._optimal_candidate = len(candidates)
            candidates.append(node)
    return candidates


class KeepSubset(ast.NodeTransformer):
    def __init__(self, retained: set[int]):
        self.retained = retained

    def visit_Call(self, node):
        self.generic_visit(node)
        index = getattr(node, "_optimal_candidate", None)
        if index is not None and index not in self.retained:
            operand = removable_operand(node)
            if operand is not None:
                return ast.copy_location(operand, node)
        return node


def materialize(base: ast.AST, retained: set[int]) -> str:
    tree = copy.deepcopy(base)
    tree = KeepSubset(retained).visit(tree)
    tree = ast.fix_missing_locations(add_imports(tree))
    return ast.unparse(tree)


def check(source: str, run_program: bool, timeout: int):
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "candidate.py"
        path.write_text(source)
        command = [
            sys.executable,
            str(ROOT / "static_runner.py"),
            str(path),
            "--require-static",
        ]
        if not run_program:
            command.append("--compile-only")
        return subprocess.run(
            command, capture_output=True, text=True, timeout=timeout)


def search(base, count: int, run_program: bool, timeout: int):
    attempts = 0
    for retained_count in range(count + 1):
        print(
            f"trying solutions with {retained_count}/{count} wrappers",
            file=sys.stderr,
        )
        for retained_tuple in itertools.combinations(range(count), retained_count):
            attempts += 1
            retained = set(retained_tuple)
            source = materialize(base, retained)
            result = check(source, run_program, timeout)
            if result.returncode == 0:
                return retained, source, result, attempts
    return None, None, None, attempts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--mask", type=lambda value: int(value, 0), default=0)
    parser.add_argument("--benchmark-granularity", action="store_true")
    parser.add_argument("--less-any", action="store_true")
    parser.add_argument("--check", choices=("compile", "run"), default="compile")
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--max-candidates", type=int, default=24)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()

    original = args.source.read_text()
    transformed = detype(
        original,
        mask=args.mask,
        bench=args.benchmark_granularity,
        less_any=args.less_any,
    )
    candidates = mark_generated_wrappers(original, transformed)
    print(f"generated removable wrappers: {len(candidates)}", file=sys.stderr)
    for index, call in enumerate(candidates):
        print(
            f"  w{index}: line {getattr(call, 'lineno', 0)} "
            f"{ast.unparse(call)[:100]}",
            file=sys.stderr,
        )

    if len(candidates) > args.max_candidates:
        raise SystemExit(
            f"refusing 2^{len(candidates)} search; increase --max-candidates"
        )

    retained, output, result, attempts = search(
        transformed,
        len(candidates),
        args.check == "run",
        args.timeout,
    )
    if retained is None:
        raise SystemExit(f"no valid subset after {attempts} attempts")

    print(f"valid after {attempts} attempts", file=sys.stderr)
    print(
        f"minimum retained wrappers: {len(retained)}/{len(candidates)} "
        f"({sorted(retained)})",
        file=sys.stderr,
    )
    if result.stdout.strip():
        print(result.stdout.rstrip(), file=sys.stderr)

    if args.output is None:
        print(output)
    else:
        args.output.write_text(output + "\n")
        print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
