"""Branch-and-bound search over coercions at graph-connected positions.

Candidate positions are every wrappable expression in the undirected
connected components containing a predicted mismatch or a wrapper generated by
the existing mediator. Candidate actions are concrete wrappers produced by
patch_picker for representations observed in those components.

The existing mediator is a valid upper bound. Search proceeds by total wrapper
count below that bound, using an in-process CinderX bind as the cheap oracle and
the Static Python loader only to confirm bind-valid candidates.
"""
from __future__ import annotations

import argparse
import ast
import copy
import itertools
import sys
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(ROOT), str(HERE)]

from detyper import detype
from inline_call_analysis import find_inline_args
from cinderx_binding import get_ast_data
from import_adder import add_imports
from patch_picker import Wrapper, _choose
from typedness_graph import CONTEXT, TYPE, build_binding_graph
from brute_force_prune import (
    KeepSubset,
    check,
    mark_generated_wrappers,
    removable_operand,
)
from print_instances import (
    find_mismatches,
    node_key,
    parse_mask,
    wrappable,
)

SENTINEL = "__coercion_value__"


@dataclass(frozen=True)
class Action:
    position: int
    cost: int
    description: str
    template_dump: str
    template: ast.AST
    origin_span: tuple
    priority: tuple


def span(node: ast.AST) -> tuple:
    return (
        getattr(node, "lineno", None),
        getattr(node, "col_offset", None),
        getattr(node, "end_lineno", None),
        getattr(node, "end_col_offset", None),
    )


class MakeTemplate(ast.NodeTransformer):
    def __init__(self, original):
        self.original = original

    def visit(self, node):
        if node is self.original:
            return ast.copy_location(ast.Name(id=SENTINEL, ctx=ast.Load()), node)
        return super().visit(node)


class FillTemplate(ast.NodeTransformer):
    def __init__(self, value):
        self.value = value

    def visit_Name(self, node):
        if node.id == SENTINEL:
            return self.value
        return node


def make_template(wrapper, original):
    return MakeTemplate(original).visit(copy.deepcopy(wrapper.next_root))


def template_call_count(template: ast.AST) -> int:
    count = 0
    node = template
    while isinstance(node, ast.Call) and node.args:
        count += 1
        node = node.args[-1]
    return max(count, 1)


def undirected_candidate_nodes(graph, roots: set[ast.AST]) -> set[ast.AST]:
    """All AST nodes connected to roots when edge direction is ignored."""
    adjacency: dict[tuple, set[tuple]] = {}
    for edge in graph.edges:
        adjacency.setdefault(edge.source, set()).add(edge.target)
        adjacency.setdefault(edge.target, set()).add(edge.source)

    pending = [(node, slot) for node in roots for slot in (TYPE, CONTEXT)]
    seen = set(pending)
    while pending:
        cell = pending.pop()
        for neighbor in adjacency.get(cell, ()):
            if neighbor not in seen:
                seen.add(neighbor)
                pending.append(neighbor)
    return {node for node, _ in seen if wrappable(node)}


def baseline_tree(mediator_tree: ast.AST) -> ast.AST:
    tree = copy.deepcopy(mediator_tree)
    tree = KeepSubset(set()).visit(tree)
    return ast.fix_missing_locations(add_imports(tree))


def baseline_positions(tree: ast.AST):
    positions = []
    for node in ast.walk(tree):
        if wrappable(node):
            node._global_position = len(positions)
            positions.append(node)
    return positions


def map_position(graph_node, positions):
    matches = [node for node in positions if span(node) == span(graph_node)]
    same_type = [node for node in matches if type(node) is type(graph_node)]
    matches = same_type or matches
    if not matches:
        return None
    # Prefer the structurally smallest expression at an ambiguous copied span.
    return min(matches, key=lambda node: len(list(ast.walk(node))))


def unique_identity(values):
    result = []
    for value in values:
        if value is not None and all(value is not old for old in result):
            result.append(value)
    return result


def build_actions(
    graph,
    bound,
    predicted,
    mismatch_map,
    candidate_nodes,
    positions,
    generated_spans,
):
    inline_args = find_inline_args(bound.tree, bound.reverse_outflow)
    component_types = unique_identity([
        value
        for mismatch in mismatch_map.values()
        for value in (mismatch.produced, mismatch.demanded)
    ])
    actions = []
    seen = set()
    for graph_node in sorted(candidate_nodes, key=node_key):
        position_node = map_position(graph_node, positions)
        produced = predicted.types.get(graph_node)
        if position_node is None or produced is None:
            continue
        targets = unique_identity([
            predicted.contexts.get(graph_node),
            bound.type_contexts.get(graph_node),
            *component_types,
        ])
        for target in targets:
            try:
                wrapper = _choose(
                    graph_node,
                    produced,
                    target,
                    bound.valid_pair,
                    inline_args,
                    bound.dynamic,
                    graph.must_agree(graph_node),
                )
            except Exception:
                continue
            if type(wrapper) is Wrapper or wrapper.T is None:
                continue
            template = make_template(wrapper, graph_node)
            dump = ast.dump(template, include_attributes=False)
            position = position_node._global_position
            key = position, dump
            if key in seen:
                continue
            seen.add(key)
            description = ast.unparse(template).replace(SENTINEL, "VALUE")
            generated = span(graph_node) in generated_spans
            local = graph_node in mismatch_map
            actions.append(Action(
                position=position,
                cost=template_call_count(template),
                description=description,
                template_dump=dump,
                template=template,
                origin_span=span(graph_node),
                priority=(not generated, not local, node_key(graph_node), description),
            ))
    return sorted(actions, key=lambda action: action.priority)


class ApplyActions(ast.NodeTransformer):
    def __init__(self, actions: dict[int, Action]):
        self.actions = actions

    def visit(self, node):
        self.generic_visit(node)
        position = getattr(node, "_global_position", None)
        action = self.actions.get(position)
        if action is None:
            return node
        template = copy.deepcopy(action.template)
        return ast.copy_location(FillTemplate(node).visit(template), node)


def materialize_tree(base: ast.AST, selected: tuple[Action, ...]) -> ast.AST:
    tree = copy.deepcopy(base)
    chosen = {action.position: action for action in selected}
    tree = ApplyActions(chosen).visit(tree)
    return ast.fix_missing_locations(add_imports(tree))


def materialize(base: ast.AST, selected: tuple[Action, ...]) -> str:
    return ast.unparse(materialize_tree(base, selected))


def bind_tree(tree: ast.AST):
    try:
        get_ast_data(copy.deepcopy(tree))
        return True, None
    except Exception as error:
        return False, error


def bind_valid(source: str) -> tuple[bool, str]:
    valid, error = bind_tree(ast.parse(source))
    return valid, "" if error is None else f"{type(error).__name__}: {error}"


def static_check(source: str, run_program: bool, timeout: int):
    return check(source, run_program, timeout)


def relevant_actions(error, graph, bound, actions):
    """Actions in the directed reverse slice of the current binder error.

    The global universe is built from undirected components, because a chosen
    coercion may create errors on either side of a dependency. Once an error is
    present, however, any action that repairs it must feed its location along a
    directed graph path. This gives the branch-and-bound search a much smaller,
    error-specific branching set.
    """
    line = getattr(error, "lineno", None)
    offset = getattr(error, "offset", None)
    targets = []
    for node in ast.walk(bound.tree):
        if getattr(node, "lineno", None) != line:
            continue
        start = getattr(node, "col_offset", 0) + 1
        end = getattr(node, "end_col_offset", start) + 1
        if offset is None or start <= offset <= end:
            targets.extend(((node, TYPE), (node, CONTEXT)))
    if not targets:
        targets = [(node, slot) for node in ast.walk(bound.tree)
                   if getattr(node, "lineno", None) == line
                   for slot in (TYPE, CONTEXT)]

    reverse = {}
    for edge in graph.edges:
        reverse.setdefault(edge.target, set()).add(edge.source)
    seen = set(targets)
    pending = list(targets)
    candidate_spans = set()
    while pending:
        cell = pending.pop()
        if wrappable(cell[0]):
            candidate_spans.add(span(cell[0]))
        for predecessor in reverse.get(cell, ()):
            if predecessor not in seen:
                seen.add(predecessor)
                pending.append(predecessor)
    relevant = [action for action in actions
                if action.origin_span in candidate_spans]
    return relevant or list(actions)


def error_directed_search(
    base, graph, bound, actions, budget, deadline, max_attempts, attempts,
):
    """Depth-first branch-and-bound with the CinderX binder as oracle."""
    memo = set()
    last_error = [None]

    def visit(selected, remaining, used_positions):
        if attempts[0] >= max_attempts or time.monotonic() >= deadline:
            return None
        state = tuple(sorted((a.position, a.template_dump) for a in selected))
        if state in memo:
            return None
        memo.add(state)
        attempts[0] += 1
        tree = materialize_tree(base, tuple(selected))
        valid, error = bind_tree(tree)
        if valid:
            return tuple(selected), ast.unparse(tree)
        last_error[0] = error
        if remaining == 0:
            return None
        branches = relevant_actions(error, graph, bound, actions)
        for action in branches:
            if action.position in used_positions or action.cost > remaining:
                continue
            used_positions.add(action.position)
            selected.append(action)
            result = visit(selected, remaining - action.cost, used_positions)
            selected.pop()
            used_positions.remove(action.position)
            if result is not None:
                return result
        return None

    result = visit([], budget, set())
    return result, last_error[0]


def tighten_mediator_bound(source, mediator, generated, final_run):
    """Use the bind oracle to minimize the known mediator wrapper set first."""
    attempts = 0
    for retained_count in range(len(generated) + 1):
        for retained in itertools.combinations(range(len(generated)), retained_count):
            attempts += 1
            tree = copy.deepcopy(mediator)
            tree = KeepSubset(set(retained)).visit(tree)
            tree = ast.fix_missing_locations(add_imports(tree))
            candidate = ast.unparse(tree)
            valid, _ = bind_valid(candidate)
            if not valid:
                continue
            confirmed = static_check(candidate, final_run, 180)
            if confirmed.returncode == 0:
                return retained_count, candidate, attempts
    return len(generated), ast.unparse(mediator), attempts


def solve(source, mask, granularity, seconds, max_attempts, final_run):
    bound = get_ast_data(ast.parse(source))
    graph = build_binding_graph(bound)
    units = graph.units(granularity)
    effective = mask or ((1 << len(units)) - 1)
    erased = graph.nodes_for_mask(effective, granularity)
    predicted = graph.settle(bound, erased)
    mismatches = find_mismatches(graph, bound, predicted)

    mediator = detype(source, mask=mask, bench=granularity == "benchmark")
    generated = mark_generated_wrappers(source, mediator)
    upper_bound, best_source, bound_attempts = tighten_mediator_bound(
        source, mediator, generated, final_run)
    generated_spans = {
        span(removable_operand(call) or call) for call in generated
    }

    base = baseline_tree(mediator)
    positions = baseline_positions(base)
    roots = set(mismatches)
    for graph_node in ast.walk(bound.tree):
        if wrappable(graph_node) and span(graph_node) in generated_spans:
            roots.add(graph_node)
    candidates = undirected_candidate_nodes(graph, roots)
    actions = build_actions(
        graph, bound, predicted, mismatches, candidates, positions,
        generated_spans)

    deadline = time.monotonic() + seconds
    attempts = [bound_attempts]
    last_error = None
    for budget in range(upper_bound):
        result, last_error = error_directed_search(
            base, graph, bound, actions, budget, deadline, max_attempts,
            attempts)
        if result is None:
            if attempts[0] >= max_attempts or time.monotonic() >= deadline:
                text = "" if last_error is None else f"{type(last_error).__name__}: {last_error}"
                return None, best_source, upper_bound, actions, attempts[0], text
            continue
        selected, candidate = result
        confirmed = static_check(candidate, final_run, 180)
        if confirmed.returncode == 0:
            return (selected, candidate), best_source, upper_bound, actions, attempts[0], ""
        # A code-generation/runtime failure is outside the bind model. Keep
        # searching larger budgets; report it if no graph-model solution works.
        last_error = RuntimeError(
            confirmed.stderr.strip().splitlines()[-1] if confirmed.stderr.strip()
            else f"static check exited {confirmed.returncode}")
    text = "" if last_error is None else f"{type(last_error).__name__}: {last_error}"
    return (None, best_source), best_source, upper_bound, actions, attempts[0], text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--mask", type=parse_mask, default=0)
    parser.add_argument(
        "--granularity", choices=("annotation", "benchmark"),
        default="annotation")
    parser.add_argument("--seconds", type=float, default=30)
    parser.add_argument("--max-attempts", type=int, default=100000)
    parser.add_argument("--run", action="store_true")
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()

    started = time.monotonic()
    result, mediator, upper, actions, attempts, error = solve(
        args.source.read_text(), args.mask, args.granularity,
        args.seconds, args.max_attempts, args.run)
    elapsed = time.monotonic() - started
    print(f"tightened mediator upper bound: {upper} wrappers", file=sys.stderr)
    print(f"candidate positions: {len({a.position for a in actions})}", file=sys.stderr)
    print(f"candidate actions: {len(actions)}", file=sys.stderr)
    print(f"bind-oracle attempts: {attempts}", file=sys.stderr)
    print(f"elapsed: {elapsed:.3f}s", file=sys.stderr)

    if result is None:
        print("search limit reached; no optimality result", file=sys.stderr)
        if error:
            print(f"last error: {error}", file=sys.stderr)
        raise SystemExit(2)
    selected, output = result
    optimum = upper if selected is None else sum(action.cost for action in selected)
    print(f"minimum wrappers: {optimum}", file=sys.stderr)
    for action in selected or ():
        print(f"  {action.description}", file=sys.stderr)
    if args.output:
        args.output.write_text(output + "\n")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
